### ISSUE TITLE
Milestone 3 Response

### ISSUE THREAD

**Issue by ebeshero** [ZSchleger/Star-Wars-Project#2]
Inspecting the project repo, there are some problems to address:

- [ ] The project website doesn't seem to be set up properly: 
     - [ ] Is it set up to publish GitHub Pages @ZSchleger ?
     - [ ] Why is there a `home.html`? That doesn't work on a real website. It should be `index.html` to be the main page of the site.
     - [ ]  Check and make sure the internal site navigation works as you add pages (link to main page always goes to `index.html` etc)

- [ ] There's a good Relax NG schema set up, but no XML files actually ready. Is there regex work going on? Can I help? 

@JaxAbele @DivinexRoyalty @ZSchleger @JordanJ7
